### ISSUE TITLE
Wire up Travis

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#52]
We should probably use Travis-CI (or circle or whatever's hot this week) to [at a minimum]:

1. Lint the code.
2. Build the add-on.

---

**Bonus points:** In Activity Stream, we also used our CI to build a "Nightly" version of the add-on which gets pushed to a special S3 bucket so people could install a "development" add-on that updates daily instead of having to build locally constantly or wait for a build to be published every 2 weeks.

Not necessary, but could be a fun experiment.

**Comment by pdehaan** [comment]
This _may_ work as a crude little Travis-CI linter (somebody would need to enable Travis for this repo):

```yaml
language: node_js

node_js:
  - 4

before_script:
  - npm i addons-linter -g

script:
  - npm run lint
  - npm run package
  - addons-linter dist/addon.xpi
```

We could also use something like [**nsp**](http://npm.im/nsp) to check for potentially vulnerable modules, but that would possibly be super-overkill for this repo considering the only dependency we have is **get-youtube-id** (which itself doesn't have any dependencies).
